import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Sun, 
  Zap, 
  Home, 
  Calculator, 
  ArrowRight, 
  ArrowLeft,
  CheckCircle2, 
  TrendingUp, 
  Leaf, 
  Info,
  ChevronRight,
  RefreshCw,
  Sparkles,
  FileDown,
  Printer
} from 'lucide-react';
import Markdown from 'react-markdown';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Slider } from '@/components/ui/slider';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { SolarSystemConfig, CalculationResults } from './types';
import { calculateSolarSystem } from './lib/solarUtils';
import { getSolarAdvice } from './services/geminiService';

export default function App() {
  const [step, setStep] = useState<'welcome' | 'inputs' | 'results'>('welcome');
  const [config, setConfig] = useState<SolarSystemConfig>({
    name: '',
    monthlyBill: 2000,
    availableSpace: 500,
    location: '',
  });
  const [results, setResults] = useState<CalculationResults | null>(null);
  const [advice, setAdvice] = useState<string | null>(null);
  const [loadingAdvice, setLoadingAdvice] = useState(false);

  // Local states for smooth typing in numeric inputs
  const [billInput, setBillInput] = useState('2000');
  const [spaceInput, setSpaceInput] = useState('500');

  const isValidText = (text: string | undefined) => {
    if (!text) return false;
    const trimmed = text.trim();
    // Simplified validation: just check length to be safe across all environments
    return trimmed.length >= 2;
  };

  const isConfigValid = () => {
    return (
      isValidText(config.name) &&
      isValidText(config.location) &&
      (config.monthlyBill ?? 0) > 0 &&
      (config.availableSpace ?? 0) > 0
    );
  };

  const handleStart = () => {
    if (isValidText(config?.name ?? '')) {
      setStep('inputs');
    }
  };

  const handleCalculate = async () => {
    if (!isConfigValid()) return;
    
    try {
      const res = calculateSolarSystem(config);
      setResults(res);
      setStep('results');
      generateAdvice(res);
    } catch (err) {
      console.error(err);
    }
  };

  const generateAdvice = async (res: CalculationResults) => {
    setLoadingAdvice(true);
    setAdvice(null);
    try {
      const aiAdvice = await getSolarAdvice(config, res);
      setAdvice(aiAdvice);
    } catch (err) {
      console.error(err);
      setAdvice("I'm sorry, I couldn't generate personalized advice right now. Please try again later.");
    } finally {
      setLoadingAdvice(false);
    }
  };

  const handleDownloadReport = () => {
    if (!results) return;
    
    const reportText = `
SOLARWISE BLUEPRINT REPORT
--------------------------
User: ${config.name}
Location: ${config.location}

CALCULATION RESULTS:
- Recommended Capacity: ${results.recommendedCapacity} kW
- Estimated Panels: ${results.estimatedPanels}
- Space Required: ${results.requiredArea} sq ft
- Estimated Cost: ₹${results.estimatedCost}
- Monthly Savings: ₹${results.monthlySavings.toFixed(0)}
- ROI Period: ${results.roiYears.toFixed(1)} years
- Carbon Offset: ${results.carbonOffset.toFixed(1)} tons CO2/year

AI ADVICE:
${advice || 'AI Advice not generated yet.'}

Generated by SolarWise Advisor on ${new Date().toLocaleDateString()}
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SolarWise_Report_${config.name.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  const SkeletonLoader = () => (
    <div className="space-y-6 p-6">
      <div className="h-8 w-1/3 shimmer rounded-lg" />
      <div className="space-y-3">
        <div className="h-4 w-full shimmer rounded" />
        <div className="h-4 w-5/6 shimmer rounded" />
        <div className="h-4 w-4/6 shimmer rounded" />
      </div>
      <div className="h-8 w-1/4 shimmer rounded-lg pt-4" />
      <div className="grid grid-cols-2 gap-4">
        <div className="h-20 shimmer rounded-xl" />
        <div className="h-20 shimmer rounded-xl" />
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-[#fafafa] text-slate-900 font-sans selection:bg-yellow-200 solar-gradient">
      <main className="relative z-10 max-w-6xl mx-auto px-4 py-12 md:py-20">
        <AnimatePresence mode="wait">
          {step === 'welcome' && (
            <motion.div
              key="welcome"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="flex flex-col items-center text-center space-y-12"
            >
              <motion.div 
                initial={{ scale: 0.8 }}
                animate={{ scale: 1 }}
                transition={{ type: "spring", stiffness: 100 }}
                className="relative"
              >
                <div className="absolute inset-0 bg-yellow-400 blur-3xl opacity-20 animate-pulse" />
                <div className="relative inline-flex items-center gap-2 px-6 py-2 rounded-full bg-white shadow-sm border border-yellow-100 text-yellow-700 font-semibold text-sm mb-4">
                  <Sun className="w-4 h-4 animate-spin-slow" />
                  <span>India's #1 Solar Advisor</span>
                </div>
              </motion.div>
              
              <div className="space-y-4">
                <h1 className="text-6xl md:text-8xl font-black tracking-tighter text-slate-900 leading-[0.9]">
                  SOLAR <span className="text-yellow-500">WISE</span>
                </h1>
                <p className="text-xl text-slate-500 max-w-xl mx-auto font-medium">
                  Smart rooftop planning with AI. 
                  Save money, save the planet.
                </p>
              </div>

              <Card className="w-full max-w-md border-none shadow-2xl bg-white/90 backdrop-blur-xl rounded-3xl overflow-hidden">
                <CardContent className="pt-10 pb-8 px-8 space-y-8">
                  <div className="space-y-3 text-left">
                    <Label htmlFor="name" className="text-xs font-bold uppercase tracking-widest text-slate-400 ml-1">Your Name</Label>
                    <Input 
                      id="name"
                      placeholder="e.g. Rahul Sharma" 
                      value={config?.name ?? ''}
                      onChange={(e) => setConfig(prev => ({ ...prev, name: e.target.value }))}
                      className="h-14 text-xl border-slate-100 bg-slate-50/50 focus:bg-white focus:ring-2 focus:ring-yellow-500 transition-all rounded-2xl"
                    />
                    {config.name.length > 0 && !isValidText(config.name) && (
                      <p className="text-[10px] text-red-400 font-bold uppercase ml-1">Min 2 letters required</p>
                    )}
                  </div>

                  <Button 
                    onClick={handleStart}
                    disabled={!isValidText(config?.name ?? '')}
                    className="w-full h-14 text-lg font-bold bg-yellow-500 hover:bg-yellow-600 text-white rounded-2xl shadow-xl shadow-yellow-200/50 transition-all active:scale-[0.98] group"
                  >
                    Start Calculation
                    <ArrowRight className="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" />
                  </Button>
                </CardContent>
              </Card>

              <div className="flex flex-wrap justify-center gap-8 pt-8">
                {[
                  { icon: Zap, label: "Fast Results" },
                  { icon: Calculator, label: "ROI Analysis" },
                  { icon: Sparkles, label: "AI Insights" }
                ].map((item, i) => (
                  <div key={i} className="flex items-center gap-2 text-slate-400 font-bold text-xs uppercase tracking-tighter">
                    <item.icon className="w-4 h-4" />
                    <span>{item.label}</span>
                  </div>
                ))}
              </div>
            </motion.div>
          )}

          {step === 'inputs' && (
            <motion.div
              key="inputs"
              initial={{ opacity: 0, x: 40 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -40 }}
              className="max-w-4xl mx-auto space-y-10"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <Button variant="outline" size="icon" onClick={() => setStep('welcome')} className="rounded-full">
                    <ArrowLeft className="w-4 h-4" />
                  </Button>
                  <div>
                    <h2 className="text-4xl font-black tracking-tight">Setup Profile</h2>
                    <p className="text-slate-500 font-medium">Details for {config?.name ?? 'your'}'s home</p>
                  </div>
                </div>
                <div className="hidden md:flex items-center gap-2 px-4 py-2 bg-white rounded-full shadow-sm border border-slate-100">
                  <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
                  <span className="text-xs font-bold text-slate-500 uppercase">Live Calculator</span>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <Card className="border-none shadow-xl bg-white/90 backdrop-blur-xl rounded-3xl">
                  <CardHeader className="pb-2">
                    <div className="flex items-center gap-3 mb-2">
                      <div className="p-2 bg-yellow-100 rounded-xl">
                        <Zap className="w-5 h-5 text-yellow-600" />
                      </div>
                      <CardTitle className="text-xl">Monthly Bill</CardTitle>
                    </div>
                    <CardDescription className="font-medium">Average monthly electricity expense</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-6 pt-4">
                    <div className="flex justify-between items-center gap-4">
                      <div className="relative flex-1">
                        <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 font-bold">₹</span>
                        <Input 
                          type="number"
                          min="1"
                          value={billInput}
                          onChange={(e) => {
                            const val = e.target.value;
                            setBillInput(val);
                            const num = Number(val);
                            if (!isNaN(num)) {
                              setConfig(prev => ({ ...prev, monthlyBill: num }));
                            }
                          }}
                          onBlur={() => {
                            if (billInput === '' || Number(billInput) <= 0) {
                              setBillInput(config.monthlyBill.toString());
                            }
                          }}
                          className="h-14 pl-8 text-2xl font-black border-slate-100 bg-slate-50/50 focus:bg-white rounded-2xl"
                        />
                      </div>
                      <span className="text-slate-400 font-bold text-sm uppercase shrink-0">INR</span>
                    </div>
                    <Slider 
                      value={[config?.monthlyBill ?? 2000]} 
                      min={100}
                      max={50000} 
                      step={100} 
                      onValueChange={(val) => {
                        setConfig(prev => ({ ...prev, monthlyBill: val[0] }));
                        setBillInput(val[0].toString());
                      }}
                      className="py-4"
                    />
                    <div className="flex flex-wrap gap-2">
                      {[2000, 5000, 10000, 15000].map(val => (
                        <Button 
                          key={val} 
                          variant="secondary" 
                          size="sm"
                          onClick={() => {
                            setConfig(prev => ({ ...prev, monthlyBill: val }));
                            setBillInput(val.toString());
                          }}
                          className={`rounded-full px-4 font-bold transition-all ${config?.monthlyBill === val ? 'bg-yellow-500 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}
                        >
                          ₹{val}
                        </Button>
                      ))}
                    </div>
                  </CardContent>
                </Card>

                <Card className="border-none shadow-xl bg-white/90 backdrop-blur-xl rounded-3xl">
                  <CardHeader className="pb-2">
                    <div className="flex items-center gap-3 mb-2">
                      <div className="p-2 bg-blue-100 rounded-xl">
                        <Home className="w-5 h-5 text-blue-600" />
                      </div>
                      <CardTitle className="text-xl">Rooftop Area</CardTitle>
                    </div>
                    <CardDescription className="font-medium">Available space for installation</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-6 pt-4">
                    <div className="flex justify-between items-center gap-4">
                      <Input 
                        type="number"
                        min="1"
                        value={spaceInput}
                        onChange={(e) => {
                          const val = e.target.value;
                          setSpaceInput(val);
                          const num = Number(val);
                          if (!isNaN(num)) {
                            setConfig(prev => ({ ...prev, availableSpace: num }));
                          }
                        }}
                        onBlur={() => {
                          if (spaceInput === '' || Number(spaceInput) <= 0) {
                            setSpaceInput(config.availableSpace.toString());
                          }
                        }}
                        className="h-14 text-2xl font-black border-slate-100 bg-slate-50/50 focus:bg-white rounded-2xl flex-1"
                      />
                      <span className="text-slate-400 font-bold text-sm uppercase shrink-0 whitespace-nowrap">Sq Ft</span>
                    </div>
                    <Slider 
                      value={[config?.availableSpace ?? 500]} 
                      min={50}
                      max={5000} 
                      step={50} 
                      onValueChange={(val) => {
                        setConfig(prev => ({ ...prev, availableSpace: val[0] }));
                        setSpaceInput(val[0].toString());
                      }}
                      className="py-4"
                    />
                    <div className="p-4 bg-blue-50/50 rounded-2xl border border-blue-100 flex gap-3 items-center">
                      <Info className="w-5 h-5 text-blue-500 shrink-0" />
                      <p className="text-sm font-medium text-blue-700">1kW system needs roughly 100 sq ft area.</p>
                    </div>
                  </CardContent>
                </Card>

                <Card className="md:col-span-2 border-none shadow-xl bg-white/90 backdrop-blur-xl rounded-3xl">
                  <CardContent className="p-8 grid md:grid-cols-2 gap-8 items-center">
                    <div className="space-y-4">
                      <div className="space-y-2">
                        <Label className="text-xs font-bold uppercase tracking-widest text-slate-400 ml-1">Your Location</Label>
                        <Input 
                          placeholder="e.g. Mumbai, Maharashtra" 
                          value={config?.location ?? ''}
                          onChange={(e) => setConfig(prev => ({ ...prev, location: e.target.value }))}
                          className="h-14 text-lg border-slate-100 bg-slate-50/50 focus:bg-white rounded-2xl"
                        />
                        {config.location.length > 0 && !isValidText(config.location) && (
                          <p className="text-[10px] text-red-400 font-bold uppercase ml-1">Min 2 letters required</p>
                        )}
                      </div>
                    </div>
                    <Button 
                      onClick={handleCalculate}
                      disabled={!isConfigValid()}
                      className="w-full h-14 text-lg font-bold bg-slate-900 hover:bg-slate-800 disabled:bg-slate-200 disabled:text-slate-400 disabled:cursor-not-allowed text-white rounded-2xl shadow-xl transition-all active:scale-[0.98]"
                    >
                      Analyze Solar Potential
                      <Sparkles className="ml-2 w-5 h-5 text-yellow-400" />
                    </Button>
                  </CardContent>
                </Card>
              </div>
            </motion.div>
          )}

          {step === 'results' && results && (
            <motion.div
              key="results"
              initial={{ opacity: 0, y: 40 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -40 }}
              className="space-y-8 pb-20"
            >
              <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
                <div className="flex items-center gap-4">
                  <Button variant="outline" size="icon" onClick={() => setStep('inputs')} className="rounded-full shrink-0">
                    <ArrowLeft className="w-4 h-4" />
                  </Button>
                  <div className="space-y-2">
                    <Badge className="bg-yellow-500 text-white border-none px-4 py-1 rounded-full font-bold uppercase tracking-tighter text-[10px]">Analysis Complete</Badge>
                    <h2 className="text-5xl font-black tracking-tighter">Your Solar Blueprint</h2>
                    <p className="text-slate-500 font-medium">Optimized for {config?.location ?? 'Unknown'}</p>
                  </div>
                </div>
                <div className="flex gap-3 print:hidden">
                  <Button 
                    variant="outline" 
                    onClick={handlePrint}
                    className="rounded-xl border-slate-200 font-bold text-slate-600 hover:bg-slate-50"
                  >
                    <Printer className="w-4 h-4 mr-2" />
                    Print
                  </Button>
                  <Button 
                    onClick={handleDownloadReport}
                    className="rounded-xl bg-slate-900 text-white font-bold hover:bg-slate-800 shadow-lg"
                  >
                    <FileDown className="w-4 h-4 mr-2" />
                    Download Report
                  </Button>
                </div>
              </div>

              {/* Bento Grid Results */}
              <div className="grid grid-cols-1 md:grid-cols-4 md:grid-rows-2 gap-4 h-auto md:h-[500px]">
                {/* Main Capacity Card */}
                <Card className="md:col-span-2 md:row-span-2 border-none shadow-2xl bg-slate-900 text-white rounded-[2.5rem] overflow-hidden relative group">
                  <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:opacity-20 transition-opacity">
                    <Sun className="w-48 h-48 animate-spin-slow" />
                  </div>
                  <CardContent className="p-10 h-full flex flex-col justify-between relative z-10">
                    <div className="space-y-6">
                      <div className="p-4 bg-white/10 w-fit rounded-2xl backdrop-blur-md">
                        <Zap className="w-8 h-8 text-yellow-400" />
                      </div>
                      <div className="space-y-2">
                        <p className="text-slate-400 font-bold uppercase tracking-widest text-xs">Recommended Capacity</p>
                        <h3 className="text-7xl font-black tracking-tighter">{results?.recommendedCapacity ?? 0} <span className="text-3xl text-yellow-500">kW</span></h3>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-8 pt-10 border-t border-white/10">
                      <div className="space-y-1">
                        <p className="text-slate-400 text-xs font-bold uppercase">Estimated Panels</p>
                        <p className="text-3xl font-black">{results?.estimatedPanels ?? 0}</p>
                      </div>
                      <div className="space-y-1">
                        <p className="text-slate-400 text-xs font-bold uppercase">Space Required</p>
                        <p className="text-3xl font-black">{results?.requiredArea ?? 0} <span className="text-sm">sqft</span></p>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Savings Card */}
                <Card className="md:col-span-2 border-none shadow-xl bg-white rounded-[2rem] overflow-hidden">
                  <CardContent className="p-8 flex items-center justify-between h-full">
                    <div className="space-y-2">
                      <p className="text-slate-400 font-bold uppercase tracking-widest text-xs">Monthly Savings</p>
                      <h3 className="text-5xl font-black tracking-tighter text-green-600">₹{results?.monthlySavings?.toFixed(0) ?? 0}</h3>
                      <p className="text-slate-400 text-sm font-medium">Reduced from ₹{config?.monthlyBill ?? 0}</p>
                    </div>
                    <div className="p-6 bg-green-50 rounded-3xl">
                      <TrendingUp className="w-10 h-10 text-green-500" />
                    </div>
                  </CardContent>
                </Card>

                {/* ROI Card */}
                <Card className="border-none shadow-xl bg-white rounded-[2rem] overflow-hidden">
                  <CardContent className="p-8 flex flex-col justify-between h-full">
                    <p className="text-slate-400 font-bold uppercase tracking-widest text-[10px]">ROI Period</p>
                    <div className="space-y-1">
                      <h3 className="text-4xl font-black tracking-tighter text-blue-600">{results?.roiYears?.toFixed(1) ?? 0}</h3>
                      <p className="text-slate-400 text-xs font-bold uppercase">Years</p>
                    </div>
                  </CardContent>
                </Card>

                {/* Eco Card */}
                <Card className="border-none shadow-xl bg-green-600 text-white rounded-[2rem] overflow-hidden">
                  <CardContent className="p-8 flex flex-col justify-between h-full">
                    <Leaf className="w-8 h-8 text-green-200" />
                    <div className="space-y-1">
                      <h3 className="text-4xl font-black tracking-tighter">{results?.carbonOffset?.toFixed(1) ?? 0}</h3>
                      <p className="text-green-200 text-[10px] font-bold uppercase leading-tight">Tons CO2 Offset / Year</p>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* AI Advisor Section */}
              <div className="grid md:grid-cols-3 gap-8">
                <div className="md:col-span-3">
                  <Card className="border-none shadow-2xl bg-white rounded-[2.5rem] overflow-hidden flex flex-col min-h-[500px]">
                    <CardHeader className="bg-slate-50 border-b border-slate-100 p-8">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                          <div className="p-3 bg-yellow-500 rounded-2xl shadow-lg shadow-yellow-200">
                            <Sparkles className="w-6 h-6 text-white" />
                          </div>
                          <div>
                            <CardTitle className="text-2xl font-black tracking-tight">AI Smart Advisor</CardTitle>
                            <CardDescription className="font-bold text-slate-400 uppercase text-[10px] tracking-widest">Powered by Gemini Flash</CardDescription>
                          </div>
                        </div>
                        <Badge variant="outline" className="rounded-full border-slate-200 text-slate-400 font-bold">BETA</Badge>
                      </div>
                    </CardHeader>
                    <CardContent className="p-0 flex-1">
                      <ScrollArea className="h-[500px]">
                        {loadingAdvice ? (
                          <SkeletonLoader />
                        ) : advice ? (
                          <div className="p-8 prose prose-slate max-w-none prose-headings:font-black prose-headings:tracking-tight prose-p:font-medium prose-li:font-medium">
                            <Markdown>{advice}</Markdown>
                            {advice.includes("I'm sorry") || advice.includes("unavailable") || advice.includes("taking too long") ? (
                              <Button 
                                variant="outline" 
                                size="sm" 
                                onClick={() => results && generateAdvice(results)}
                                className="mt-4 rounded-xl border-yellow-200 text-yellow-700 hover:bg-yellow-50"
                              >
                                <RefreshCw className="w-4 h-4 mr-2" />
                                Retry AI Analysis
                              </Button>
                            ) : null}
                          </div>
                        ) : (
                          <div className="flex flex-col items-center justify-center h-full py-20 text-slate-300">
                            <Sparkles className="w-12 h-12 mb-4 opacity-20" />
                            <p className="font-bold uppercase tracking-widest text-xs">Waiting for insights...</p>
                          </div>
                        )}
                      </ScrollArea>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      {/* Footer */}
      <footer className="relative z-10 border-t border-slate-200 bg-white/50 backdrop-blur-md py-8 mt-20">
        <div className="max-w-4xl mx-auto px-4 flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-yellow-500 rounded-lg flex items-center justify-center text-white font-bold">S</div>
            <span className="font-bold text-slate-900">SolarWise</span>
          </div>
          <p className="text-slate-500 text-sm">© 2026 SolarWise Advisor. Go Solar. Save Future.</p>
          <div className="flex gap-6">
            <a href="#" className="text-slate-400 hover:text-slate-600 text-sm transition-colors">Privacy</a>
            <a href="#" className="text-slate-400 hover:text-slate-600 text-sm transition-colors">Terms</a>
            <a href="#" className="text-slate-400 hover:text-slate-600 text-sm transition-colors">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
